name: Deploy Cluster

on:
  workflow_dispatch:
  
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{'${{'}} secrets.TF_API_TOKEN ${{'}}'}}" 

      - name: Initialize Terraform
        run: | 
          terraform init

      - name: Terraform apply
        run: |
           terraform apply 