name: Deploy Cluster

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{'${{'}} secrets.TF_API_TOKEN ${{'}}'}}"  
          
      - name: Initialize Terraform
        run:  terraform init
      
      - name: Terraform apply
        run: terraform apply 