apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.componentId | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{ values.repoUrl }}
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: build.yml
spec:
  type: service
  lifecycle: development
  owner: ${{values.owner | dump}}
