apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: kong_ingress
  title: Kong Ingress Controller Template
  description: Configure a Kong API Gateway installation
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform-templates
    - vkpr
    - kong
    - aws
spec:
  owner: veecode/platform
  type: devops
  parameters:
       ### Project Configuration
    - title: Project Configuration
      required:
        - componentId
        - owner
      properties:
        componentId:
          title: Project name
          type: string
          description: Name of the project
          ui:autofocus: true
          ui:field: EntityNamePicker
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

     ### Kong Configuration
    - title: Kong Configuration
      required:
        - domain
        - kong_mode
        - basic_auth

      properties:
        domain:
          title: Domain to use 
          type: string
          description: Specifies the Domain to use on manager an admin API's endpoint.
        kong_mode:
          title: Do you want to use Kong with database?
          type: string
          description: Specifies if you want to install Kong with database.
          default: "dbless"
          enum:
            - "dbless"
            - "standard"
        basic_auth:
          title: Do you want to use the basic-auth plugin to close Kong's admin API?
          type: boolean
          description: If you don't have a Kong license This will leave the Kong admin API open, Do you want to set up basic authentication?
          default: false

     ### Location Configuration
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          description: Choose a location to create the Access Stack Pipeline
          ui:field: RepoUrlPlatform
          ui:options:
            allowedHosts:
              - github.com
              - gitlab.com

        visibility:
          title: Repository visibility
          type: string
          enum:
            - public
            - private
          enumNames:
            - 'Public'
            - 'Private'
          default: private
          
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton      
        values:
          domain: ${{ parameters.domain }}
          kong_mode: ${{ parameters.kong_mode }}
          basic_auth: ${{ parameters.basic_auth }}
          specPublish: ${{ (parameters.specPublish | parseRepoUrl).owner }}/${{ (parameters.specPublish | parseRepoUrl).repo }}
          specPublishRepo: ${{ (parameters.specPublish | parseRepoUrl).repo }}
          specPublishBranch: ${{ parameters.specPublishBranch }}
          specTags: ${{ parameters.specTags }}
          owner: ${{ parameters.owner }}
          repoUrl: ${{ (parameters.repoUrl | parseRepoUrl).owner }}/${{ (parameters.repoUrl | parseRepoUrl).repo }}
          componentId: ${{ parameters.componentId }}
          host: ${{ (parameters.repoUrl | parseRepoUrl).host }}

    # check github
    - name: Check Github Provider
      if: ${{ (parameters.repoUrl | parseRepoUrl).host === "github.com" }} 
      action: fs:delete
      input:
        files: 
          - ./.gitlab-ci.yml 
    # check gitlab
    - name: Check Gitlab Provider
      if: ${{ (parameters.repoUrl | parseRepoUrl).host === "gitlab.com" }} 
      action: fs:delete
      input:
        files:
          - ./.github
  
    - id: publish
      name: Publish in Github
      if: ${{ (parameters.repoUrl | parseRepoUrl).host  === "github.com" }} 
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: This is ${{ parameters.componentId }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: ${{ parameters.visibility }}
      
    - id: publish
      name: Publish in Gitlab
      if: ${{ (parameters.repoUrl | parseRepoUrl).host  === "gitlab.com" }}
      action: publish:gitlab
      input:
        allowedHosts:
          - gitlab.com
        description: This is ${{ parameters.componentId }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: ${{ parameters.visibility }} 

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml