image:
  name: hashicorp/terraform:light
  entrypoint: [""]

stages:
  - deploy
  - destroy


variables:
  TF_ROOT: $CI_PROJECT_DIR
  DEPLOY_JOB: 'false'
  DESTROY_JOB: 'false'

deploy:
  stage: deploy
  script:
    - terraform --version
    - terraform init
    - terraform init -backend-config="token=${TF_API_TOKEN}" -reconfigure
    - terraform apply 
  rules:
    - if: '$DEPLOY_JOB == "true"'
  artifacts:
    name: kubeconf
    paths:
      - kube/* 
    expire_in: 1 day

destroy:
  stage: destroy
  script:
    - terraform --version
    - terraform init -backend-config="token=${TF_API_TOKEN}" -reconfigure
    - terraform destroy 
  rules:
    - if: '$DESTROY_JOB == "true"'

