---
cluster_name: "${{ values.cluster_name }}"
VCP_ID: "${{ values.VCP }}"
publicsCIDRblock: "${{ values.subnet }}"
availabilityZone: "${{ values.availabilityZone }}"
instance_type: "${{ values.instance_type }}"
keypar: "${{ values.keypair }}"
