apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.componentId }}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    {%- if values.host.includes("github") %}
    github.com/project-slug: ${{ values.repoUrl }}
    {%- endif %}
    {%- if values.host.includes("gitlab") %}
    gitlab.com/project-slug: ${{ values.repoUrl }}
    {%- endif %}
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: ${{values.componentId | dump}}
    vault.io/secrets-path: ${{values.componentId | dump}}
    grafana/tag-selector: ${{values.componentId | dump}}
    grafana/alert-label-selector: "alertname=${{values.componentId}}"
    argocd/proxy-url: '/argocd/api'
    argocd/app-name: ${{values.componentId | dump}}
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}



